### PR TITLE
Proposal for DewPointDevice implementation

### PR DESCRIPTION
**Pull request by mwittig**
Hi, here is my proposal for the DewPointDevice implementation. I have tried to simplify it as much as possibe. See also the simplified device configuration in README.md. As I have no temperature/humidity sensor to test with I have used some other numeric variables which works great. Each time, the temperature or humidity value changes, the doYourStuff() method will be invoked to calc the dewpoint value. Note, for some reason it does not work with the readings from the openweather plugin. I think it is a bug in the Pimatic framework as it does work with the VariablesManager either. See also http://forum.pimatic.org/topic/396/pimatic-openweather-variable-problem-with-pimatic-pushover

### CODE REVIEW

**Comment by flybysun** [comment]
Hi, thank you very much for you commitment! I'm just testing it with a DHT22 sensor and it works perfect. The code is now a lot shorter and the plugin is more easy to be added to the config.json. I just merged it to my original files. I still have to edit the formula a bit (the fixed numbers change when the temperature is 0°C or below 0°C) but then the plugin should be ready to use. After that I would like to share it with the pimatic comunity. Any idea how to do this?

**Comment by mwittig** [comment]
See my comment http://forum.pimatic.org/topic/348/dew-point-plugin-that-calculates-the-dew-point-from-other-devices/23

**Comment by mwittig** [comment]
Maybe you should also add a note in the README that the temperature reading must be degree Celsius! It won't work for Fahrenheit, but the plugin could be extended in the future to do so. This just came to my mind as some users will use imperial measurements units with their sensors - see also http://forum.pimatic.org/topic/440/imperial-measurements-but-temperatures-still-show-c/4

**Comment by mwittig** [comment]
Just a note: package.json contains a version number which is current set as follows: "version": "0.9.0"
This version number will be the version number of your npm package.

**Comment by flybysun** [comment]
Well I'm a bit new to this github and npm things, but I will read the
howtos and see how things work. I already edited the readme in my master
branch a bit, but for the other things I will have a look at it later. I
guess this afternoon or so.

2015-05-12 8:47 GMT+02:00 Marcus Wittig notifications@github.com:

**Pull request merged**
